# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
cloud_name: test
title: Guten Rug Studio
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Guten Rug studio. Here, you can find unique, stylish, and handmade rugs that will perfectly fit your house or apartment. Explore our completed projects and get inspired
baseurl: ""
url: "https://gutenrugtuftingstudio.com/"
# baseurl: ""
# url: ""
twitter_username: guten_rug
github_username: guten_rug

# Build settings
remote_theme: raviriley/agency-jekyll-theme
# theme: jekyll-agency
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
languages: ["en", "pl"]
default_lang: "en"
exclude_from_localizations: ["assets", "css", "js"]
default_locale_in_subfolder: false
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
    values:
      lang: "en"
