# Jekyll configuration file
cloud_name: test
title: Guten Rug Studio
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Guten Rug studio. Here, you can find unique, stylish, and handmade rugs that will perfectly fit your house or apartment. Explore our completed projects and get inspired
baseurl: ""
url: "https://gutenrugtuftingstudio.com/"
# baseurl: ""
# url: ""
twitter_username: guten_rug
github_username: guten_rug

# Build settings
# remote_theme: raviriley/agency-jekyll-theme
theme: jekyll-agency
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
languages: ["en", "pl"]
default_lang: "en"
exclude_from_localizations: ["assets", "css", "js"]
default_locale_in_subfolder: false
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
    values:
      lang: "en"